-- ADL Cafe backend. Paste into the Supabase SQL Editor and run once.
--
-- What the app can do with the publishable key:
--   * read menu_items
--   * call place_order()
-- Nothing else. orders and order_lines get no grants and no RLS policies, so
-- the API cannot read, edit or delete them; staff see them in the dashboard.
-- place_order() is SECURITY DEFINER, which is how it writes to them anyway.
--
-- Money is integer cents throughout, as in the app.

-- ---- Menu -------------------------------------------------------------------

create table public.menu_items (
  -- "by default" so the seed below can pin ids that match the app's offline
  -- seed (SeedData.kt, inserted in the same order), while rows added later in
  -- the dashboard still get one generated.
  id           bigint generated by default as identity primary key,
  name         text    not null,
  description  text    not null default '',
  category     text    not null,
  price_cents  int     not null check (price_cents >= 0),
  emoji        text    not null default '',
  sizable      boolean not null default true,
  is_popular   boolean not null default false,
  is_available boolean not null default true
);

alter table public.menu_items enable row level security;

create policy "Anyone can read the menu"
  on public.menu_items for select
  to anon, authenticated
  using (true);

grant select on public.menu_items to anon, authenticated;

-- ---- Orders -----------------------------------------------------------------

create table public.orders (
  id             bigint generated always as identity primary key,
  order_number   text        not null default '',
  placed_at      timestamptz not null default now(),
  customer_name  text        not null check (length(customer_name) between 1 and 100),
  -- Enum names, matching how the app persists OrderType / OrderStatus.
  order_type     text        not null check (order_type in ('PICKUP', 'DINE_IN')),
  note           text        not null default '' check (length(note) <= 500),
  subtotal_cents int         not null default 0,
  tax_cents      int         not null default 0,
  total_cents    int         not null default 0,
  status         text        not null default 'PLACED'
                 check (status in ('PLACED', 'PREPARING', 'READY', 'COMPLETED'))
);

-- Like OrderLine in the app, lines snapshot the item at order time, so editing
-- or deleting a menu item never rewrites an old order.
create table public.order_lines (
  id               bigint generated always as identity primary key,
  order_id         bigint  not null references public.orders (id) on delete cascade,
  menu_item_id     bigint  references public.menu_items (id) on delete set null,
  item_name        text    not null,
  emoji            text    not null,
  size             text    not null check (size in ('SMALL', 'MEDIUM', 'LARGE')),
  sizable          boolean not null,
  quantity         int     not null check (quantity between 1 and 99),
  unit_price_cents int     not null
);

create index order_lines_order_id_idx on public.order_lines (order_id);

alter table public.orders      enable row level security;
alter table public.order_lines enable row level security;

-- ---- place_order ------------------------------------------------------------

-- Takes item ids, sizes and quantities, never prices: prices come from
-- menu_items here, so a modified client cannot order a latte for 0 cents.
--
-- Everything below runs in the one transaction PostgREST wraps the call in, so
-- an exception anywhere leaves no order, no half-written lines, nothing.
--
-- These rules are duplicated from the app and must stay in step with it:
--   size surcharges -> DrinkSize.surchargeCents  (0 / 60 / 120)
--   tax rate        -> Pricing.TAX_BASIS_POINTS  (850 = 8.5%, half-up)
-- The app's checkout screen shows its own estimate; the receipt it stores is
-- the one returned from here.
create or replace function public.place_order(
  p_customer_name text,
  p_order_type    text,
  p_note          text,
  p_items         jsonb   -- [{"menu_item_id": 1, "size": "MEDIUM", "quantity": 2}, ...]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id bigint;
  v_subtotal bigint;
  v_tax      bigint;
  v_order    public.orders;
begin
  if jsonb_typeof(p_items) is distinct from 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'An order needs at least one item';
  end if;
  if jsonb_array_length(p_items) > 50 then
    raise exception 'Too many lines in one order';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as i(menu_item_id bigint, size text, quantity int)
    left join public.menu_items m on m.id = i.menu_item_id and m.is_available
    where m.id is null
  ) then
    raise exception 'Something in your cart is no longer on the menu';
  end if;

  insert into public.orders (customer_name, order_type, note)
  values (trim(p_customer_name), p_order_type, coalesce(trim(p_note), ''))
  returning id into v_order_id;

  -- Food is always SMALL with no surcharge. An unknown size makes the price
  -- NULL, which the NOT NULL on unit_price_cents rejects.
  insert into public.order_lines
    (order_id, menu_item_id, item_name, emoji, size, sizable, quantity, unit_price_cents)
  select
    v_order_id, m.id, m.name, m.emoji,
    case when m.sizable then i.size else 'SMALL' end,
    m.sizable,
    i.quantity,
    m.price_cents + case
      when not m.sizable      then 0
      when i.size = 'SMALL'  then 0
      when i.size = 'MEDIUM' then 60
      when i.size = 'LARGE'  then 120
    end
  from rows from (
         jsonb_to_recordset(p_items) as (menu_item_id bigint, size text, quantity int)
       ) with ordinality as i(menu_item_id, size, quantity, n)
  join public.menu_items m on m.id = i.menu_item_id
  order by i.n;

  select coalesce(sum(l.unit_price_cents::bigint * l.quantity), 0)
    into v_subtotal
    from public.order_lines l
   where l.order_id = v_order_id;

  -- Half-up in integer arithmetic, same as Pricing.taxOn.
  v_tax := (v_subtotal * 850 + 5000) / 10000;

  -- The ::int casts raise on overflow rather than storing a wrapped total.
  update public.orders o
     set order_number   = 'ADL-' || (1000 + v_order_id)::text,
         subtotal_cents = v_subtotal::int,
         tax_cents      = v_tax::int,
         total_cents    = (v_subtotal + v_tax)::int
   where o.id = v_order_id
  returning o.* into v_order;

  return jsonb_build_object(
    'order_number',    v_order.order_number,
    'placed_at_millis', (extract(epoch from v_order.placed_at) * 1000)::bigint,
    'subtotal_cents',  v_order.subtotal_cents,
    'tax_cents',       v_order.tax_cents,
    'total_cents',     v_order.total_cents,
    'lines', (
      select jsonb_agg(jsonb_build_object(
               'item_name',        l.item_name,
               'emoji',            l.emoji,
               'size',             l.size,
               'sizable',          l.sizable,
               'quantity',         l.quantity,
               'unit_price_cents', l.unit_price_cents
             ) order by l.id)
      from public.order_lines l
      where l.order_id = v_order_id
    )
  );
end;
$$;

revoke execute on function public.place_order(text, text, text, jsonb) from public;
grant  execute on function public.place_order(text, text, text, jsonb) to anon, authenticated;

-- ---- Seed -------------------------------------------------------------------

-- Same items, same order, same ids as SeedData.kt.
insert into public.menu_items
  (id, name, description, category, price_cents, emoji, sizable, is_popular)
values
  (1, 'House Drip', 'Our daily rotating single origin, brewed batch-style.', 'Coffee', 320, '☕', true, true),
  (2, 'Pour Over', 'Hand poured to order over a V60. Takes about four minutes.', 'Coffee', 480, '☕', true, false),
  (3, 'Americano', 'Double shot cut with hot water.', 'Espresso', 350, '☕', true, false),
  (4, 'Latte', 'Double shot with steamed milk and a thin cap of foam.', 'Espresso', 450, '🥛', true, true),
  (5, 'Cappuccino', 'Equal parts espresso, steamed milk and foam.', 'Espresso', 430, '☕', true, false),
  (6, 'Flat White', 'Ristretto shots with velvety microfoam.', 'Espresso', 460, '🥛', true, false),
  (7, 'Mocha', 'Espresso, dark chocolate and steamed milk.', 'Espresso', 495, '🍫', true, false),
  (8, 'Cortado', 'Espresso cut with an equal measure of warm milk.', 'Espresso', 400, '☕', true, false),
  (9, 'Cold Brew', 'Steeped eighteen hours, served over ice.', 'Cold Brew', 460, '🧊', true, true),
  (10, 'Nitro Cold Brew', 'Nitrogen infused for a soft, cascading pour.', 'Cold Brew', 540, '🧊', true, false),
  (11, 'Iced Latte', 'Double shot poured over cold milk and ice.', 'Cold Brew', 470, '🧋', true, false),
  (12, 'Earl Grey', 'Ceylon black tea with bergamot.', 'Tea', 300, '🍵', true, false),
  (13, 'Green Sencha', 'Grassy Japanese green tea, brewed at 80°C.', 'Tea', 320, '🍵', true, false),
  (14, 'Masala Chai', 'Black tea simmered with cardamom, ginger and clove.', 'Tea', 380, '🫖', true, true),
  (15, 'Butter Croissant', 'Laminated overnight, baked each morning.', 'Pastries', 340, '🥐', false, true),
  (16, 'Pain au Chocolat', 'Two batons of dark chocolate in butter pastry.', 'Pastries', 375, '🥐', false, false),
  (17, 'Blueberry Muffin', 'Sour cream crumb muffin packed with berries.', 'Pastries', 330, '🧁', false, false),
  (18, 'Cinnamon Roll', 'Soft brioche roll with cream cheese glaze.', 'Pastries', 420, '🍥', false, false),
  (19, 'Avocado Toast', 'Sourdough, smashed avocado, chilli and lemon.', 'Food', 780, '🥑', false, false),
  (20, 'Halloumi Sandwich', 'Grilled halloumi, roast pepper and rocket in ciabatta.', 'Food', 890, '🥪', false, false),
  (21, 'Breakfast Bagel', 'Egg, cheddar and smoked paprika mayo.', 'Food', 820, '🥯', false, false);

-- The explicit ids above do not advance the identity sequence.
select setval(pg_get_serial_sequence('public.menu_items', 'id'),
              (select max(id) from public.menu_items));
