package com.adl.cafe.data

import androidx.room.withTransaction
import com.adl.cafe.data.dao.CartDao
import com.adl.cafe.data.dao.MenuDao
import com.adl.cafe.data.dao.OrderDao
import com.adl.cafe.data.model.CartItem
import com.adl.cafe.data.model.CartLine
import com.adl.cafe.data.model.DrinkSize
import com.adl.cafe.data.model.MenuItem
import com.adl.cafe.data.model.OrderEntity
import com.adl.cafe.data.model.OrderLine
import com.adl.cafe.data.model.OrderType
import com.adl.cafe.data.model.OrderWithLines
import com.adl.cafe.data.remote.CafeRemote
import kotlinx.coroutines.flow.Flow

/**
 * The single place the UI talks to for data. ViewModels depend on this, never
 * on the DAOs directly, so the storage layer stays swappable.
 *
 * Room is what the UI observes. [remote] is the source of truth for the menu
 * (copied into Room by [refreshMenu]) and where orders are actually placed.
 */
class CafeRepository(
    private val database: AppDatabase,
    private val menuDao: MenuDao,
    private val cartDao: CartDao,
    private val orderDao: OrderDao,
    private val remote: CafeRemote
) {

    /**
     * Populates the menu on first launch so the app has something to show
     * before (or without) its first [refreshMenu]. Safe to call on every start.
     * Autogenerated ids come out 1..n in list order, which the server's seed
     * matches, so cart lines added offline still point at the right items.
     */
    suspend fun seedIfEmpty() {
        if (menuDao.count() == 0) {
            menuDao.insertAll(SeedData.menu)
        }
    }

    /**
     * Replaces the local menu with the server's. Items gone from the server are
     * deleted here too, which cascades them out of the cart.
     */
    suspend fun refreshMenu() {
        val items = remote.fetchMenu()
        // An empty response is far likelier a misconfigured table or policy than
        // a cafe with nothing to sell; wiping the menu would not help anyone.
        if (items.isEmpty()) return
        database.withTransaction {
            menuDao.upsertAll(items)
            menuDao.deleteAllExcept(items.map { it.id })
        }
    }

    // ---- Menu -------------------------------------------------------------

    fun observeCategories(): Flow<List<String>> = menuDao.observeCategories()

    fun observeMenu(category: String?, query: String): Flow<List<MenuItem>> =
        menuDao.observeMenu(category, query.trim())

    fun observeMenuItem(id: Long): Flow<MenuItem?> = menuDao.observeById(id)

    // ---- Cart -------------------------------------------------------------

    fun observeCartLines(): Flow<List<CartLine>> = cartDao.observeCartLines()

    fun observeCartCount(): Flow<Int> = cartDao.observeCartCount()

    /**
     * Adding an item already in the cart at the same size bumps its quantity.
     *
     * The lookup and the write must share a transaction: two quick-adds racing
     * would otherwise both see no existing row and both insert, and the unique
     * index on (menuItemId, size) turns the loser into a constraint crash.
     */
    suspend fun addToCart(menuItemId: Long, size: DrinkSize, quantity: Int) {
        database.withTransaction {
            val existing = cartDao.findLine(menuItemId, size)
            if (existing == null) {
                cartDao.insert(CartItem(menuItemId = menuItemId, size = size, quantity = quantity))
            } else {
                cartDao.update(existing.copy(quantity = existing.quantity + quantity))
            }
        }
    }

    /** A quantity of zero or less removes the line entirely. */
    suspend fun setCartQuantity(cartItemId: Long, quantity: Int) {
        val lines = cartDao.getCartLines()
        val target = lines.firstOrNull { it.cartItem.id == cartItemId } ?: return
        if (quantity <= 0) {
            cartDao.delete(target.cartItem)
        } else {
            cartDao.update(target.cartItem.copy(quantity = quantity))
        }
    }

    suspend fun removeFromCart(cartItemId: Long) = cartDao.deleteById(cartItemId)

    suspend fun clearCart() = cartDao.clear()

    // ---- Orders -----------------------------------------------------------

    fun observeOrders(): Flow<List<OrderWithLines>> = orderDao.observeOrders()

    fun observeOrder(orderId: Long): Flow<OrderWithLines?> = orderDao.observeOrder(orderId)

    /**
     * Sends the cart to the server as an order, then stores the receipt it
     * returns and empties the cart. Returns the new local order id, or null if
     * the cart was empty. Throws if the server did not accept the order, in
     * which case nothing local has changed and the cart is intact for a retry.
     *
     * The server prices and numbers the order atomically on its side, so the
     * stored receipt is the server's, not the checkout screen's estimate. The
     * local writes then share one transaction: split up, a failure partway
     * through could leave an order with no lines, or a placed order whose cart
     * was never cleared.
     */
    suspend fun placeOrder(
        customerName: String,
        orderType: OrderType,
        note: String
    ): Long? {
        val lines = cartDao.getCartLines()
        if (lines.isEmpty()) return null

        val name = customerName.trim()
        val trimmedNote = note.trim()
        val placed = remote.placeOrder(name, orderType, trimmedNote, lines)

        return database.withTransaction {
            val orderId = orderDao.insertOrder(
                OrderEntity(
                    orderNumber = placed.orderNumber,
                    placedAtMillis = placed.placedAtMillis,
                    customerName = name,
                    orderType = orderType,
                    note = trimmedNote,
                    subtotalCents = placed.subtotalCents,
                    taxCents = placed.taxCents,
                    totalCents = placed.totalCents
                )
            )

            orderDao.insertLines(
                placed.lines.map { line ->
                    OrderLine(
                        orderId = orderId,
                        itemName = line.itemName,
                        emoji = line.emoji,
                        size = line.size,
                        sizable = line.sizable,
                        quantity = line.quantity,
                        unitPriceCents = line.unitPriceCents
                    )
                }
            )

            cartDao.clear()
            orderId
        }
    }
}
